@agentMemoryServerUrl = http://localhost:8000
@userId = user-2bfc7e6e-452f-40d6-b7e7-29855518B052

POST {{agentMemoryServerUrl}}/v1/long-term-memory/
Content-Type: application/json

{
  "memories": [
    {
      "id": "{{userId}}",
      "session_id": "{{userId}}",
      "text": "My favorite programming language is Java",
      "namespace": "long-term-memory",
      "memory_type": "semantic"
    }
  ]
}
